name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mise à jour vers v4

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Mise à jour vers v3
        with:
          node-version: '20'  # Utilisation de Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Display Node.js version
        run: node -v  # Cette étape affiche la version de Node.js utilisée

      - name: Prepare build directory
        run: |
          mkdir -p build
          cp -r * build
          cd build
          echo 'pb38550.github.io' > CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

=======
  - name: Checkout
    uses: actions/checkout@v4  # Mise à jour vers v4

  - name: Setup Node.js
    uses: actions/setup-node@v3  # Mise à jour vers v3
    with:
      node-version: '20'  # Utilisation de Node.js 20

  - name: Setup Pages
    uses: actions/configure-pages@v5

  - name: Display Node.js version
    run: node -v  # Cette étape affiche la version de Node.js utilisée

  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: '.'

  - name: Deploy to GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4
>>>>>>> 8657109a0fb621b15714eb2ad1dbfedc91378efa
